// <auto-generated />
using System;
using GoblinFarm.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Migrations
{
    [DbContext(typeof(GoblinFarmContext))]
    partial class GoblinFarmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("GoblinFarm.EF.TelldusAccumulatedSensorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DataUnit")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DataValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ElectricityCost_KwH_Ore")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("TelldusAccumulatedSensorLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
